// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld.proto

package helloworld

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SimpleData struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleData) Reset()         { *m = SimpleData{} }
func (m *SimpleData) String() string { return proto.CompactTextString(m) }
func (*SimpleData) ProtoMessage()    {}
func (*SimpleData) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{2}
}

func (m *SimpleData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleData.Unmarshal(m, b)
}
func (m *SimpleData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleData.Marshal(b, m, deterministic)
}
func (m *SimpleData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleData.Merge(m, src)
}
func (m *SimpleData) XXX_Size() int {
	return xxx_messageInfo_SimpleData.Size(m)
}
func (m *SimpleData) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleData.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleData proto.InternalMessageInfo

func (m *SimpleData) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ServerStreamData struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerStreamData) Reset()         { *m = ServerStreamData{} }
func (m *ServerStreamData) String() string { return proto.CompactTextString(m) }
func (*ServerStreamData) ProtoMessage()    {}
func (*ServerStreamData) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{3}
}

func (m *ServerStreamData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerStreamData.Unmarshal(m, b)
}
func (m *ServerStreamData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerStreamData.Marshal(b, m, deterministic)
}
func (m *ServerStreamData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerStreamData.Merge(m, src)
}
func (m *ServerStreamData) XXX_Size() int {
	return xxx_messageInfo_ServerStreamData.Size(m)
}
func (m *ServerStreamData) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerStreamData.DiscardUnknown(m)
}

var xxx_messageInfo_ServerStreamData proto.InternalMessageInfo

func (m *ServerStreamData) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
	proto.RegisterType((*SimpleData)(nil), "helloworld.SimpleData")
	proto.RegisterType((*ServerStreamData)(nil), "helloworld.ServerStreamData")
}

func init() { proto.RegisterFile("helloworld.proto", fileDescriptor_17b8c58d586b62f2) }

var fileDescriptor_17b8c58d586b62f2 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xd1, 0x4b, 0xc3, 0x30,
	0x10, 0xc6, 0x1b, 0x14, 0x67, 0x3f, 0x14, 0xca, 0x09, 0x52, 0x8a, 0x88, 0x04, 0x91, 0x3d, 0x8d,
	0x51, 0xdf, 0x05, 0x51, 0x50, 0xf1, 0x45, 0xd2, 0xbf, 0x20, 0x9b, 0xc7, 0x1c, 0x24, 0x36, 0xa6,
	0x51, 0xe9, 0x7f, 0x2f, 0x6d, 0x57, 0xd6, 0x49, 0xf5, 0xed, 0xee, 0xbb, 0x5f, 0xee, 0xbe, 0x8f,
	0x20, 0x79, 0x63, 0x63, 0xca, 0xef, 0xd2, 0x9b, 0xd7, 0x99, 0xf3, 0x65, 0x28, 0x09, 0x5b, 0x45,
	0x4a, 0x1c, 0x3d, 0x36, 0x9d, 0xe2, 0x8f, 0x4f, 0xae, 0x02, 0x11, 0xf6, 0xdf, 0xb5, 0xe5, 0x54,
	0x5c, 0x88, 0x69, 0xac, 0xda, 0x5a, 0x5e, 0x01, 0x1b, 0xc6, 0x99, 0x9a, 0x52, 0x4c, 0x2c, 0x57,
	0x95, 0x5e, 0xf5, 0x50, 0xdf, 0xca, 0x73, 0xa0, 0x58, 0x5b, 0x67, 0xf8, 0x5e, 0x07, 0x4d, 0x09,
	0xf6, 0x6c, 0xb5, 0xda, 0x30, 0x4d, 0x29, 0x2f, 0x91, 0x14, 0xec, 0xbf, 0xd8, 0x17, 0xc1, 0xb3,
	0xb6, 0xe3, 0x54, 0xfe, 0x84, 0xc9, 0x83, 0x67, 0x0e, 0xec, 0xe9, 0x06, 0x87, 0x85, 0xae, 0xdb,
	0xdb, 0x94, 0xce, 0x06, 0x39, 0x86, 0x96, 0xb3, 0xd3, 0x91, 0x89, 0x33, 0xb5, 0x8c, 0x72, 0x85,
	0xe3, 0xce, 0x50, 0x73, 0x76, 0xbd, 0x64, 0xba, 0x45, 0xdc, 0x09, 0xea, 0xe5, 0x8e, 0x76, 0xde,
	0x6d, 0x8d, 0x67, 0x7f, 0xe8, 0x32, 0x9a, 0x8a, 0xb9, 0xc8, 0x17, 0x38, 0x19, 0x86, 0xe8, 0x37,
	0x3f, 0x23, 0xee, 0x04, 0xe5, 0x96, 0x74, 0xb6, 0xb3, 0xe1, 0x57, 0xe4, 0xec, 0xdf, 0xa9, 0x8c,
	0xe6, 0x62, 0x71, 0xd0, 0xfe, 0xd3, 0xf5, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaf, 0xad, 0xa9,
	0x8b, 0xbb, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}

// SimpleServiceClient is the client API for SimpleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SimpleServiceClient interface {
	SimpleRPC(ctx context.Context, opts ...grpc.CallOption) (SimpleService_SimpleRPCClient, error)
}

type simpleServiceClient struct {
	cc *grpc.ClientConn
}

func NewSimpleServiceClient(cc *grpc.ClientConn) SimpleServiceClient {
	return &simpleServiceClient{cc}
}

func (c *simpleServiceClient) SimpleRPC(ctx context.Context, opts ...grpc.CallOption) (SimpleService_SimpleRPCClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SimpleService_serviceDesc.Streams[0], "/helloworld.SimpleService/SimpleRPC", opts...)
	if err != nil {
		return nil, err
	}
	x := &simpleServiceSimpleRPCClient{stream}
	return x, nil
}

type SimpleService_SimpleRPCClient interface {
	Send(*SimpleData) error
	Recv() (*SimpleData, error)
	grpc.ClientStream
}

type simpleServiceSimpleRPCClient struct {
	grpc.ClientStream
}

func (x *simpleServiceSimpleRPCClient) Send(m *SimpleData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *simpleServiceSimpleRPCClient) Recv() (*SimpleData, error) {
	m := new(SimpleData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SimpleServiceServer is the server API for SimpleService service.
type SimpleServiceServer interface {
	SimpleRPC(SimpleService_SimpleRPCServer) error
}

func RegisterSimpleServiceServer(s *grpc.Server, srv SimpleServiceServer) {
	s.RegisterService(&_SimpleService_serviceDesc, srv)
}

func _SimpleService_SimpleRPC_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SimpleServiceServer).SimpleRPC(&simpleServiceSimpleRPCServer{stream})
}

type SimpleService_SimpleRPCServer interface {
	Send(*SimpleData) error
	Recv() (*SimpleData, error)
	grpc.ServerStream
}

type simpleServiceSimpleRPCServer struct {
	grpc.ServerStream
}

func (x *simpleServiceSimpleRPCServer) Send(m *SimpleData) error {
	return x.ServerStream.SendMsg(m)
}

func (x *simpleServiceSimpleRPCServer) Recv() (*SimpleData, error) {
	m := new(SimpleData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _SimpleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.SimpleService",
	HandlerType: (*SimpleServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SimpleRPC",
			Handler:       _SimpleService_SimpleRPC_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "helloworld.proto",
}

// ServerStreamServiceClient is the client API for ServerStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerStreamServiceClient interface {
	StreamRpc(ctx context.Context, in *ServerStreamData, opts ...grpc.CallOption) (ServerStreamService_StreamRpcClient, error)
}

type serverStreamServiceClient struct {
	cc *grpc.ClientConn
}

func NewServerStreamServiceClient(cc *grpc.ClientConn) ServerStreamServiceClient {
	return &serverStreamServiceClient{cc}
}

func (c *serverStreamServiceClient) StreamRpc(ctx context.Context, in *ServerStreamData, opts ...grpc.CallOption) (ServerStreamService_StreamRpcClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ServerStreamService_serviceDesc.Streams[0], "/helloworld.ServerStreamService/StreamRpc", opts...)
	if err != nil {
		return nil, err
	}
	x := &serverStreamServiceStreamRpcClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ServerStreamService_StreamRpcClient interface {
	Recv() (*ServerStreamData, error)
	grpc.ClientStream
}

type serverStreamServiceStreamRpcClient struct {
	grpc.ClientStream
}

func (x *serverStreamServiceStreamRpcClient) Recv() (*ServerStreamData, error) {
	m := new(ServerStreamData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServerStreamServiceServer is the server API for ServerStreamService service.
type ServerStreamServiceServer interface {
	StreamRpc(*ServerStreamData, ServerStreamService_StreamRpcServer) error
}

func RegisterServerStreamServiceServer(s *grpc.Server, srv ServerStreamServiceServer) {
	s.RegisterService(&_ServerStreamService_serviceDesc, srv)
}

func _ServerStreamService_StreamRpc_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServerStreamData)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServerStreamServiceServer).StreamRpc(m, &serverStreamServiceStreamRpcServer{stream})
}

type ServerStreamService_StreamRpcServer interface {
	Send(*ServerStreamData) error
	grpc.ServerStream
}

type serverStreamServiceStreamRpcServer struct {
	grpc.ServerStream
}

func (x *serverStreamServiceStreamRpcServer) Send(m *ServerStreamData) error {
	return x.ServerStream.SendMsg(m)
}

var _ServerStreamService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.ServerStreamService",
	HandlerType: (*ServerStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamRpc",
			Handler:       _ServerStreamService_StreamRpc_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "helloworld.proto",
}
